baseURL = "https://infosec-iitgoa.netlify.app"
disableLanguages = ["fr"]
disqusShortname = ""
paginate = "4"
summaryLength = "30"
theme = "InfoSec-Website"
title = "InfoSec | IIT Goa"
[Languages.en]
contentDir = "content/english"
copyright = "[InfoSec IIT Goa](https://infosec-iitgoa.netlify.app/)"
languageCode = "en-us"
languageName = "En"
weight = 1
[[Languages.en.menu.footer]]
URL = "about"
name = "About"
weight = 1
[[Languages.en.menu.footer]]
URL = "contact"
name = "Contact"
weight = 6
[[Languages.en.menu.main]]
URL = "/"
name = "Home"
weight = 1
[[Languages.en.menu.main]]
URL = "about"
name = "About"
weight = 2
[[Languages.en.menu.main]]
URL = "contact"
name = "Contact"
weight = 7
[Languages.fr]
contentDir = "content/french"
copyright = "Copyright &copy; 2020 [Themefisher](https://themefisher.com) All Rights Reserved"
languageCode = "fr-fr"
languageName = "Fr"
weight = 2
[[Languages.fr.menu.footer]]
URL = "about"
name = "About"
weight = 1
[[Languages.fr.menu.footer]]
URL = "project"
name = "Project"
weight = 2
[[Languages.fr.menu.footer]]
URL = "service"
name = "Service"
weight = 3
[[Languages.fr.menu.footer]]
URL = "pricing"
name = "Pricing"
weight = 4
[[Languages.fr.menu.footer]]
URL = "faq"
name = "FAQ"
weight = 5
[[Languages.fr.menu.footer]]
URL = "contact"
name = "Contact"
weight = 6
[[Languages.fr.menu.main]]
URL = "/"
name = "Accueil"
weight = 1
[[Languages.fr.menu.main]]
URL = "about"
name = "À propos"
weight = 2
[[Languages.fr.menu.main]]
URL = "project"
name = "Projet"
weight = 3
[[Languages.fr.menu.main]]
URL = "service"
name = "Un service"
weight = 4
[[Languages.fr.menu.main]]
URL = "blog"
name = "Blog"
weight = 5
[[Languages.fr.menu.main]]
hasChildren = true
name = "Pages"
weight = 6
[[Languages.fr.menu.main]]
URL = "faq"
name = "FAQ"
parent = "Pages"
[[Languages.fr.menu.main]]
URL = "pricing"
name = "Tarification"
parent = "Pages"
[[Languages.fr.menu.main]]
URL = "contact"
name = "Contact"
weight = 7
[markup.goldmark.renderer]
unsafe = true
[outputs]
home = ["HTML"]
[params]
author = "Themefisher"
contact_form_action = "mailto:infosec-club@iitgoa.ac.in"
description = "Official Website of InfoSec IIT Goa"
email = "infosec-club@iitgoa.ac.in"
google_analitycs_id = ""
location = "IIT Goa Campus, Farmagudi,Ponda-Goa"
logo = "images/logo.png"
logo_width = "30px"
mobile = "0124857985320"
multi_author = false
[params.gmap]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
map_latitude = "15.422563"
map_longitude = "73.979737"
map_marker = "images/marker.png"
[params.nav_button]
enable = true
label = "Get A Quote"
link = "contact"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/Ionicons/css/ionicons.min.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
[params.preloader]
enable = true
preloader = ""
[params.widgets]
sidebar = ["recent_posts", "taxonomy_category", "taxonomy_tags"]
[[params.social]]
icon = "ion-social-youtube-outline"
link = "https://www.youtube.com/channel/UCERghQSAf19ebaPDch0JFnQ"
[[params.social]]
icon = "ion-social-instagram-outline"
link = "https://www.instagram.com/infosec_iitgoa/"
[[params.social]]
icon = "ion-social-linkedin-outline"
link = "#"
[[params.social]]
icon = "ion-social-facebook-outline"
link = "#"
